apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
  labels:
    app: django-app
spec:
  selector:
    matchLabels:
      project: django-proj
  template:
    metadata:
      labels:
        project: django-proj
    spec:
      containers:
        - name: django-app-1
          image: django_app:latest
          env:
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: DEBUG
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: SECRET_KEY
          - name: ALLOWED_HOSTS
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: ALLOWED_HOSTS
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-secrets
                key: DATABASE_URL
          imagePullPolicy: Never
          ports:
            - containerPort: 80

