apiVersion: v1
kind: Service
metadata:
  name: static-web-service
  namespace: edu-gloomy-ptolemy
spec:
  type: NodePort
  selector:
    entity: static-web
  ports:
    - protocol: TCP
      nodePort: 30007
      port: 80
      targetPort: 80