apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-django-sessions
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60
  ttlSecondsAfterFinished: 10000
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: clear-sessions
              image: django_app:latest
              command: [ "python3", "manage.py", "clearsessions" ]
              env:
                - name: DEBUG
                  valueFrom:
                    secretKeyRef:
                      name: django-secrets
                      key: DEBUG
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: django-secrets
                      key: SECRET_KEY
                - name: ALLOWED_HOSTS
                  valueFrom:
                    secretKeyRef:
                      name: django-secrets
                      key: ALLOWED_HOSTS
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: django-secrets
                      key: DATABASE_URL
              imagePullPolicy: Never
