apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-django-sessions
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60
  ttlSecondsAfterFinished: 10000
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: clear-sessions
              image: django_app:latest
              command: [ "python3", "manage.py", "clearsessions" ]
              envFrom:
                - secretRef:
                    name: django-secrets
              imagePullPolicy: Never
