apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: django-migrate
          image: django_app:latest
          command: [ "python3", "manage.py", "migrate" ]
          envFrom:
            - secretRef:
                name: django-secrets
          imagePullPolicy: Never